application:
  bindAddress: :8449
  production: false
  debug: false
authentication:
  authority: https://algotiqa-server:8443/auth/realms/algotiqa
messaging:
  address: localhost:8450
  username: admin
  password: admin
